// Common short English words — easy to read and spell aloud
export const WORDS = [
  "apple", "river", "cloud", "happy", "bright", "moon", "spark", "coffee",
  "north", "wind", "coral", "bridge", "forest", "lemon", "maple", "tiger",
  "ocean", "pearl", "sunset", "garden", "planet", "silver", "golden", "purple",
  "orange", "yellow", "green", "blue", "stone", "flame", "ember", "frost",
  "snow", "rain", "storm", "thunder", "light", "shadow", "dream", "magic",
  "castle", "dragon", "knight", "shield", "sword", "arrow", "eagle", "falcon",
  "hawk", "wolf", "bear", "fox", "deer", "rabbit", "turtle", "dolphin",
  "whale", "shark", "penguin", "parrot", "robin", "sparrow", "crane", "heron",
  "lotus", "bamboo", "cedar", "pine", "oak", "willow", "cherry", "blossom",
  "meadow", "valley", "canyon", "cliff", "peak", "summit", "trail", "path",
  "road", "lane", "harbor", "anchor", "sail", "boat", "ship", "voyage",
  "compass", "signal", "beacon", "tower", "cabin", "house", "door", "window",
  "table", "chair", "book", "page", "story", "poem", "song", "dance",
  "music", "rhythm", "melody", "harmony", "canvas", "paint", "brush", "color",
  "pixel", "rocket", "orbit", "star", "comet", "galaxy", "cosmos", "nova",
  "atom", "energy", "power", "spark", "volt", "circuit", "chip", "code",
  "logic", "matrix", "vector", "pixel", "server", "cloud", "network", "signal",
  "secure", "guard", "vault", "lock", "key", "ring", "crown", "jewel",
  "ruby", "jade", "amber", "crystal", "marble", "granite", "copper", "bronze",
  "steel", "iron", "metal", "forge", "hammer", "anvil", "wheel", "engine",
  "motor", "turbo", "rapid", "swift", "quick", "brave", "bold", "calm",
  "quiet", "gentle", "kind", "warm", "cool", "fresh", "crisp", "sweet",
  "honey", "sugar", "spice", "pepper", "mint", "basil", "olive", "bread",
  "toast", "butter", "cheese", "pasta", "rice", "noodle", "soup", "salad",
  "fruit", "berry", "grape", "melon", "peach", "mango", "coconut", "banana",
  "carrot", "tomato", "potato", "onion", "garlic", "ginger", "cinnamon", "vanilla",
  "spring", "summer", "autumn", "winter", "morning", "evening", "midnight", "sunrise",
  "horizon", "breeze", "mist", "fog", "dawn", "dusk", "twilight", "daylight",
  "anchor", "paddle", "stream", "creek", "pond", "lake", "island", "beach",
  "coast", "shore", "wave", "tide", "shell", "sand", "dune", "oasis",
  "desert", "jungle", "swamp", "marsh", "field", "farm", "barn", "fence",
  "gate", "arch", "pillar", "column", "statue", "fountain", "plaza", "market",
  "shop", "store", "corner", "block", "street", "avenue", "bridge", "tunnel",
  "station", "platform", "ticket", "travel", "journey", "ticket", "passport", "luggage",
  "pilot", "captain", "crew", "team", "squad", "group", "party", "guest",
  "friend", "buddy", "pal", "mate", "family", "home", "nest", "haven",
  "retreat", "refuge", "shelter", "comfort", "peace", "trust", "faith", "hope",
  "grace", "charm", "luck", "fortune", "treasure", "prize", "award", "medal",
  "trophy", "victor", "winner", "hero", "legend", "saga", "tale", "myth",
  "fable", "oracle", "prophet", "sage", "wizard", "witch", "fairy", "elf",
  "dwarf", "giant", "titan", "spirit", "ghost", "phantom", "shadow", "mirror",
  "glass", "lens", "focus", "vision", "sight", "view", "scene", "stage",
  "actor", "player", "coach", "mentor", "teacher", "student", "pupil", "class",
  "lesson", "study", "learn", "think", "idea", "notion", "concept", "theory",
  "fact", "truth", "proof", "reason", "sense", "mind", "brain", "heart",
  "soul", "life", "birth", "growth", "bloom", "flourish", "thrive", "prosper",
] as const;

export const WORD_LIST: string[] = [...new Set(WORDS)];
